development:
  adapter: postgresql
  database: teamworks_dev
  min_messages: warning
  
  # comment/remove these lines if running WSL on Windows
  #host: localhost
  #username:

test:
  adapter: postgresql
  database: teamworks_test
  min_messages: warning

  # comment/remove these lines if running WSL on Windows
  #host: localhost
  #username: